version: '3.8'

services:
  app:
    container_name: unirent-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT
      - DATABASE_URL
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
    ports:
      - '${APP_PORT}:${APP_PORT}'
    restart: always
    networks:
      - unirent

networks:
  unirent:
    driver: bridge
