version: '3.8'

services:
  app:
    container_name: unirent-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT
      - DATABASE_URL
    ports:
      - '${APP_PORT}:${APP_PORT}'
    restart: always
    networks:
      - unirent

networks:
  unirent:
    driver: bridge
