name: Deploy to Self-Hosted

on:
  workflow_run:
    workflows: [Build and Test]
    branches: ['main']
    types:
      - completed

env:
  APP_PORT: ${{ secrets.APP_PORT }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Build the docker-compose stack
        run: docker compose up -d --build

      - name: Clear all docker unused cache
        run: docker system prune -a
